# Generated by Django 5.0.13 on 2025-03-17 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("nomor", models.CharField(max_length=255)),
                ("pemilik", models.CharField(max_length=255)),
                ("saldo", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("nominal", models.IntegerField()),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Piutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("nominal", models.IntegerField()),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("foto", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("pemasukan", "Pemasukan"),
                            ("pengeluaran", "Pengeluaran"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("keterangan", models.TextField()),
                ("bukti", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.bank"
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="keuangan.kategori",
                    ),
                ),
            ],
        ),
    ]
