# Generated by Django 5.0.13 on 2025-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaksi",
            name="nominal",
            field=models.BigIntegerField(default=0),
        ),
    ]
