# Generated by Django 5.0.13 on 2025-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0002_transaksi_nominal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaksi",
            name="tanggal",
            field=models.DateTimeField(),
        ),
    ]
